# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bc5f2a73e8b564f7907b5a1d371c6e6ed1f40f2166ff26bf09c1f281dcc986ec519df2c28090de6a46af1619facc5a77139e8609066ed00a66640fb565ecb0d

test:
  secret_key_base: 489010d2b512ea052600a2f8c20a3ff4129eeaa1866f25bb4469376d088229f867112cfc6a182cb488318a508b26aa582019bf8ea1960f7552dc9805baf8f082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
